version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ../finantrack-backend
    ports:
      - "8000:8000"
    volumes:
      - ../finantrack-backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
